service:
  name: ac-notification-bot-ts

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: ac-notification-bot-ts

functions:
  acNotification:
    handler: handler.acNotification

